In [6]:
import torch

x = torch.tensor([[2.0, 3.0], [4.0, 5.0]], requires_grad=True)
y = torch.tensor([[1.0, 1.0], [2.0, 2.0]], requires_grad=True)

# Forward
z = x - y
z.retain_grad()  # Tells PyTorch NOT to delete this grad
o = torch.square(z)
o.retain_grad()  # Tells PyTorch NOT to delete this grad
loss = torch.sum(o)

# Backward
loss.backward()

print(f"1. Grad at 'o' (from Sum): \n{o.grad}")
print(f"2. Grad at 'z' (from Square): \n{z.grad}") # This is 2*z
print(f"3. Grad at 'x' (Final): \n{x.grad}")     # This is z.grad * 1

1. Grad at 'o' (from Sum): 
tensor([[1., 1.],
        [1., 1.]])
2. Grad at 'z' (from Square): 
tensor([[2., 4.],
        [4., 6.]])
3. Grad at 'x' (Final): 
tensor([[2., 4.],
        [4., 6.]])
